{"timestamp": "2025-06-14T15:53:23.311864", "premises": ["all x. (PerformInSchoolTalentShowsOften(x) -> AttendAndEngageWithSchoolEvents(x))", "all x. ((PerformInSchoolTalentShowsOften(x) & -InactiveAndDisinterestedMember(x)) | InactiveAndDisinterestedMember(x))", "all x. (ChaperoneHighSchoolDances(x) -> -StudentWhoAttendsSchool(x))", "all x. (InactiveAndDisinterestedMember(x) -> ChaperoneHighSchoolDances(x))", "all x. all y. (YoungChildOrTeenager(x) & WishToFurtherAcademicCareer(x) & y(wishToFurtherEducationalOpportunities(x, y)) -> StudentWhoAttendsSchool(x))", "(AttendAndEngageWithSchoolEvents(Bonnie) & StudentWhoAttendsSchool(Bonnie)) | ((-AttendAndEngageWithSchoolEvents(Bonnie)) & (-StudentWhoAttendsSchool(Bonnie)))"], "conclusion": "(-AttendAndEngageWithSchoolEvents(Bonnie)) & (-StudentWhoAttendsSchool(Bonnie)) -> -PerformInSchoolTalentShowsOften(Bonnie) & -PerformInSchoolTalentShowsOften(Bonnie)", "error_type": "<class 'nltk.sem.logic.LogicalExpressionException'>", "error_message": "'y' is an illegal predicate name.  Individual variables may not be used as predicates.\nall x. all y. (YoungChildOrTeenager(x) & WishToFurtherAcademicCareer(x) & y(wishToFurtherEducationalOpportunities(x, y)) -> StudentWhoAttendsSchool(x))\n                                                                          ^", "stack_trace": "Traceback (most recent call last):\n  File \"/data/gpfs/projects/punim0478/bansaab/linc2/eval/tasks/owafoltask.py\", line 568, in _process_neurosymbolic\n    parsed = json.loads(gen)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/json/__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 154, in parse\n    result = self.process_next_expression(None)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 290, in process_next_expression\n    accum = self.handle(tok, context)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 312, in handle\n    return self.handle_quant(tok, context)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 427, in handle_quant\n    accum = self.process_next_expression(tok)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 290, in process_next_expression\n    accum = self.handle(tok, context)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 312, in handle\n    return self.handle_quant(tok, context)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 427, in handle_quant\n    accum = self.process_next_expression(tok)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 290, in process_next_expression\n    accum = self.handle(tok, context)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 315, in handle\n    return self.handle_open(tok, context)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 449, in handle_open\n    accum = self.process_next_expression(None)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 297, in process_next_expression\n    return self.attempt_adjuncts(accum, context)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 323, in attempt_adjuncts\n    expression = self.attempt_BooleanExpression(expression, context)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 485, in attempt_BooleanExpression\n    factory, expression, self.process_next_expression(tok)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 290, in process_next_expression\n    accum = self.handle(tok, context)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 303, in handle\n    return self.handle_variable(tok, context)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 342, in handle_variable\n    raise LogicalExpressionException(\nnltk.sem.logic.LogicalExpressionException: 'y' is an illegal predicate name.  Individual variables may not be used as predicates.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/data/gpfs/projects/punim0478/bansaab/linc2/eval/tasks/utils.py\", line 214, in evaluate\n    p_list = [read_expr(p) for p in premises]\n  File \"/data/gpfs/projects/punim0478/bansaab/linc2/eval/tasks/utils.py\", line 214, in <listcomp>\n    p_list = [read_expr(p) for p in premises]\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 957, in fromstring\n    return cls._logic_parser.parse(s, signature)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 159, in parse\n    raise LogicalExpressionException(None, msg) from e\nnltk.sem.logic.LogicalExpressionException: 'y' is an illegal predicate name.  Individual variables may not be used as predicates.\nall x. all y. (YoungChildOrTeenager(x) & WishToFurtherAcademicCareer(x) & y(wishToFurtherEducationalOpportunities(x, y)) -> StudentWhoAttendsSchool(x))\n                                                                          ^\n"}
{"timestamp": "2025-06-14T15:55:22.641141", "premises": ["all x. (PerformInSchoolTalentShowsOften(x) -> AttendSchoolEvents(x) & VeryEngagedWithSchoolEvents(x))", "all x. ((PerformInSchoolTalentShowsOften(x) & -InactiveAndDisinterestedInCommunity(x)) | (-PerformInSchoolTalentShowsOften(x) & InactiveAndDisinterestedInCommunity(x)))", "all x. (ChaperoneHighSchoolDances(x) -> -StudentWhoAttendsSchool(x))", "all x. (InactiveAndDisinterestedInCommunity(x) -> ChaperoneHighSchoolDances(x))", "all x. all y. ((YoungChild(x) & Teenager(x) & WishToFurtherAcademicCareer(x) & WishToFurtherEducationalOpportunities(x)) -> StudentWhoAttendsSchool(x))", "((AttendSchoolEvents(Bonnie) & VeryEngagedWithSchoolEvents(Bonnie) & StudentWhoAttendsSchool(Bonnie)) | (-AttendSchoolEvents(Bonnie) & -VeryEngagedWithSchoolEvents(Bonnie) & -StudentWhoAttendsSchool(Bonnie)))"], "conclusion": "((((YoungChild(Bonnie) & Teenager(Bonnie) & WishToFurtherAcademicCareer(Bonnie) & WishToFurtherEducationalOpportunities(Bonnie) & ChaperoneHighSchoolDances(Bonnie)) -> (StudentWhoAttendsSchool(Bonnie) | InactiveAndDisinterestedInCommunity(Bonnie))) & ((-YoungChild(Bonnie) & -Teenager(Bonnie) & -WishToFurtherAcademicCareer(Bonnie) & -WishToFurtherEducationalOpportunities(Bonnie) & ChaperoneHighSchoolDances(Bonnie)) -> (StudentWhoAttendsSchool(Bonnie) | InactiveAndDisinterestedInCommunity(Bonnie))))", "error_type": "<class 'nltk.sem.logic.LogicalExpressionException'>", "error_message": "End of input found.  Expected token ')'.\n((((YoungChild(Bonnie) & Teenager(Bonnie) & WishToFurtherAcademicCareer(Bonnie) & WishToFurtherEducationalOpportunities(Bonnie) & ChaperoneHighSchoolDances(Bonnie)) -> (StudentWhoAttendsSchool(Bonnie) | InactiveAndDisinterestedInCommunity(Bonnie))) & ((-YoungChild(Bonnie) & -Teenager(Bonnie) & -WishToFurtherAcademicCareer(Bonnie) & -WishToFurtherEducationalOpportunities(Bonnie) & ChaperoneHighSchoolDances(Bonnie)) -> (StudentWhoAttendsSchool(Bonnie) | InactiveAndDisinterestedInCommunity(Bonnie))))\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ^", "stack_trace": "Traceback (most recent call last):\n  File \"/data/gpfs/projects/punim0478/bansaab/linc2/eval/tasks/owafoltask.py\", line 568, in _process_neurosymbolic\n    parsed = json.loads(gen)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/json/__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 270, in token\n    tok = self._buffer[self._currentIndex]\nIndexError: list index out of range\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 562, in assertNextToken\n    tok = self.token()\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 276, in token\n    raise ExpectedMoreTokensException(self._currentIndex + 1) from e\nnltk.sem.logic.ExpectedMoreTokensException: End of input found.  More tokens expected.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 154, in parse\n    result = self.process_next_expression(None)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 290, in process_next_expression\n    accum = self.handle(tok, context)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 315, in handle\n    return self.handle_open(tok, context)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 450, in handle_open\n    self.assertNextToken(Tokens.CLOSE)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 564, in assertNextToken\n    raise ExpectedMoreTokensException(\nnltk.sem.logic.ExpectedMoreTokensException: End of input found.  Expected token ')'.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/data/gpfs/projects/punim0478/bansaab/linc2/eval/tasks/utils.py\", line 213, in evaluate\n    c = read_expr(conclusion)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 957, in fromstring\n    return cls._logic_parser.parse(s, signature)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 159, in parse\n    raise LogicalExpressionException(None, msg) from e\nnltk.sem.logic.LogicalExpressionException: End of input found.  Expected token ')'.\n((((YoungChild(Bonnie) & Teenager(Bonnie) & WishToFurtherAcademicCareer(Bonnie) & WishToFurtherEducationalOpportunities(Bonnie) & ChaperoneHighSchoolDances(Bonnie)) -> (StudentWhoAttendsSchool(Bonnie) | InactiveAndDisinterestedInCommunity(Bonnie))) & ((-YoungChild(Bonnie) & -Teenager(Bonnie) & -WishToFurtherAcademicCareer(Bonnie) & -WishToFurtherEducationalOpportunities(Bonnie) & ChaperoneHighSchoolDances(Bonnie)) -> (StudentWhoAttendsSchool(Bonnie) | InactiveAndDisinterestedInCommunity(Bonnie))))\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ^\n"}
{"timestamp": "2025-06-14T15:55:22.660675", "premises": ["all x. (PerformInSchoolTalentShows(x) -> AttendAndEngage(x))", "all x. (PerformInSchoolTalentShows(x) | InactiveDisinterested(x))", "all x. (ChaperoneHighSchoolDances(x) -> -StudentAttends(x))", "all x. (InactiveDisinterested(x) -> ChaperoneHighSchoolDances(x))", "all x. (Young(x) & WishToFurtherAcademicOpportunities(x) -> StudentAttends(x))", "(AttendAndEngage(Bonnie) & StudentAttends(Bonnie)) | (-AttendAndEngage(Bonnie) & -StudentAttends(Bonnie))"], "conclusion": "((Young(Bonnie) & WishToFurtherAcademicOpportunities(Bonnie) & ChaperoneHighSchoolDances(Bonnie)) | (-Young(Bonnie) & -WishToFurtherAcademicOpportunities(Bonnie))) -> ((StudentAttends(Bonnie) | InactiveDisinterested(Bonnie))", "error_type": "<class 'nltk.sem.logic.LogicalExpressionException'>", "error_message": "End of input found.  Expected token ')'.\n((Young(Bonnie) & WishToFurtherAcademicOpportunities(Bonnie) & ChaperoneHighSchoolDances(Bonnie)) | (-Young(Bonnie) & -WishToFurtherAcademicOpportunities(Bonnie))) -> ((StudentAttends(Bonnie) | InactiveDisinterested(Bonnie))\n                                                                                                                                                                                                                                ^", "stack_trace": "Traceback (most recent call last):\n  File \"/data/gpfs/projects/punim0478/bansaab/linc2/eval/tasks/owafoltask.py\", line 568, in _process_neurosymbolic\n    parsed = json.loads(gen)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/json/__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 270, in token\n    tok = self._buffer[self._currentIndex]\nIndexError: list index out of range\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 562, in assertNextToken\n    tok = self.token()\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 276, in token\n    raise ExpectedMoreTokensException(self._currentIndex + 1) from e\nnltk.sem.logic.ExpectedMoreTokensException: End of input found.  More tokens expected.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 154, in parse\n    result = self.process_next_expression(None)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 297, in process_next_expression\n    return self.attempt_adjuncts(accum, context)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 323, in attempt_adjuncts\n    expression = self.attempt_BooleanExpression(expression, context)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 485, in attempt_BooleanExpression\n    factory, expression, self.process_next_expression(tok)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 290, in process_next_expression\n    accum = self.handle(tok, context)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 315, in handle\n    return self.handle_open(tok, context)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 450, in handle_open\n    self.assertNextToken(Tokens.CLOSE)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 564, in assertNextToken\n    raise ExpectedMoreTokensException(\nnltk.sem.logic.ExpectedMoreTokensException: End of input found.  Expected token ')'.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/data/gpfs/projects/punim0478/bansaab/linc2/eval/tasks/utils.py\", line 213, in evaluate\n    c = read_expr(conclusion)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 957, in fromstring\n    return cls._logic_parser.parse(s, signature)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 159, in parse\n    raise LogicalExpressionException(None, msg) from e\nnltk.sem.logic.LogicalExpressionException: End of input found.  Expected token ')'.\n((Young(Bonnie) & WishToFurtherAcademicOpportunities(Bonnie) & ChaperoneHighSchoolDances(Bonnie)) | (-Young(Bonnie) & -WishToFurtherAcademicOpportunities(Bonnie))) -> ((StudentAttends(Bonnie) | InactiveDisinterested(Bonnie))\n                                                                                                                                                                                                                                ^\n"}
{"timestamp": "2025-06-14T15:55:22.666347", "premises": ["all x. (Perform(x, talentshows) & Often(x) -> Attend(x, schoolevents) & VeryEngaged(x, schoolevents))", "all x. ((-Perform(x, talentshows) & Often(x)) -> Inactive(x) & Disinterested(x))", "all x. (Chaperone(x, highschooldances) -> Not(Student(x) & Attend(x, school)))", "all x. (Inactive(x) & Disinterested(x) -> Chaperone(x, highschooldances))", "all x. (Wish(x, academicopportunities) & Young(x) -> Student(x) & Attend(x, school))", "(Attend(Bonnie, schoolevents) & VeryEngaged(Bonnie, schoolevents) & Student(Bonnie) & Attend(Bonnie, school)) | (-Attend(Bonnie, schoolevents) & -VeryEngaged(Bonnie, schoolevents) & -Student(Bonnie))"], "conclusion": "((Wish(Bonnie, academicopportunities) & Young(Bonnie) & Chaperone(Bonnie, highschooldances)) | (-Wish(Bonnie, academicopportunities) & -Young(Bonnie))) -> ((Student(Bonnie) & Attend(Bonnie, school)) | (Inactive(Bonnie) & Disinterested(Bonnie)))", "error_type": "<class 'nltk.sem.logic.LogicalExpressionException'>", "error_message": "Unexpected token: '&'.  Expected token ')'.\nall x. (Chaperone(x, highschooldances) -> Not(Student(x) & Attend(x, school)))\n                                                         ^", "stack_trace": "Traceback (most recent call last):\n  File \"/data/gpfs/projects/punim0478/bansaab/linc2/eval/tasks/owafoltask.py\", line 568, in _process_neurosymbolic\n    parsed = json.loads(gen)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/json/__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 154, in parse\n    result = self.process_next_expression(None)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 290, in process_next_expression\n    accum = self.handle(tok, context)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 312, in handle\n    return self.handle_quant(tok, context)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 427, in handle_quant\n    accum = self.process_next_expression(tok)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 290, in process_next_expression\n    accum = self.handle(tok, context)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 315, in handle\n    return self.handle_open(tok, context)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 449, in handle_open\n    accum = self.process_next_expression(None)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 297, in process_next_expression\n    return self.attempt_adjuncts(accum, context)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 323, in attempt_adjuncts\n    expression = self.attempt_BooleanExpression(expression, context)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 485, in attempt_BooleanExpression\n    factory, expression, self.process_next_expression(tok)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 290, in process_next_expression\n    accum = self.handle(tok, context)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 303, in handle\n    return self.handle_variable(tok, context)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 359, in handle_variable\n    self.assertNextToken(Tokens.CLOSE)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 573, in assertNextToken\n    raise UnexpectedTokenException(self._currentIndex, tok, expected)\nnltk.sem.logic.UnexpectedTokenException: Unexpected token: '&'.  Expected token ')'.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/data/gpfs/projects/punim0478/bansaab/linc2/eval/tasks/utils.py\", line 214, in evaluate\n    p_list = [read_expr(p) for p in premises]\n  File \"/data/gpfs/projects/punim0478/bansaab/linc2/eval/tasks/utils.py\", line 214, in <listcomp>\n    p_list = [read_expr(p) for p in premises]\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 957, in fromstring\n    return cls._logic_parser.parse(s, signature)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 159, in parse\n    raise LogicalExpressionException(None, msg) from e\nnltk.sem.logic.LogicalExpressionException: Unexpected token: '&'.  Expected token ')'.\nall x. (Chaperone(x, highschooldances) -> Not(Student(x) & Attend(x, school)))\n                                                         ^\n"}
{"timestamp": "2025-06-14T16:41:52.136358", "premises": ["all x. (PerformInSchoolTalentShowsOften(x) -> AttendAndEngagedInSchoolEvents(x))", "all x. ((PerformInSchoolTalentShowsOften(x) | InactiveAndDisinterested(x)) & -InactiveAndDisinterested(x) -> PerformInSchoolTalentShowsOften(x))", "all x. (ChaperoneHighSchoolDances(x) -> -StudentWhoAttendsSchool(x))", "all x. (InactiveAndDisinterested(x) -> ChaperoneHighSchoolDances(x))", "all x. (YoungChildOrTeenager(x) & WishToFurtherAcademicCareer(x) & WishToFurtherEducationalOpportunities(x) -> StudentWhoAttendsSchool(x))", "all x. ((AttendAndEngagedInSchoolEvents(Bonnie) & StudentWhoAttendsSchool(Bonnie)) | ((-AttendAndEngagedInSchoolEvents(Bonnie)) & (-StudentWhoAttendsSchool(Bonnie))))"], "conclusion": "all x. ((AttendAndEngagedInSchoolEvents(Bonnie) & StudentWhoAttendsSchool(Bonnie)) | ((-AttendAndEngagedInSchoolEvents(Bonnie)) & (-StudentWhoAttendsSchool(Bonnie))) ->", "error_type": "<class 'nltk.sem.logic.LogicalExpressionException'>", "error_message": "End of input found.  Expression expected.\nall x. ((AttendAndEngagedInSchoolEvents(Bonnie) & StudentWhoAttendsSchool(Bonnie)) | ((-AttendAndEngagedInSchoolEvents(Bonnie)) & (-StudentWhoAttendsSchool(Bonnie))) ->\n                                                                                                                                                                        ^", "stack_trace": "Traceback (most recent call last):\n  File \"/data/gpfs/projects/punim0478/bansaab/linc2/eval/tasks/owafoltask.py\", line 568, in _process_neurosymbolic\n    parsed = json.loads(gen)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/json/__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 270, in token\n    tok = self._buffer[self._currentIndex]\nIndexError: list index out of range\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 284, in process_next_expression\n    tok = self.token()\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 276, in token\n    raise ExpectedMoreTokensException(self._currentIndex + 1) from e\nnltk.sem.logic.ExpectedMoreTokensException: End of input found.  More tokens expected.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 154, in parse\n    result = self.process_next_expression(None)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 290, in process_next_expression\n    accum = self.handle(tok, context)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 312, in handle\n    return self.handle_quant(tok, context)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 427, in handle_quant\n    accum = self.process_next_expression(tok)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 290, in process_next_expression\n    accum = self.handle(tok, context)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 315, in handle\n    return self.handle_open(tok, context)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 449, in handle_open\n    accum = self.process_next_expression(None)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 297, in process_next_expression\n    return self.attempt_adjuncts(accum, context)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 323, in attempt_adjuncts\n    expression = self.attempt_BooleanExpression(expression, context)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 485, in attempt_BooleanExpression\n    factory, expression, self.process_next_expression(tok)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 286, in process_next_expression\n    raise ExpectedMoreTokensException(\nnltk.sem.logic.ExpectedMoreTokensException: End of input found.  Expression expected.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/data/gpfs/projects/punim0478/bansaab/linc2/eval/tasks/utils.py\", line 213, in evaluate\n    c = read_expr(conclusion)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 957, in fromstring\n    return cls._logic_parser.parse(s, signature)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 159, in parse\n    raise LogicalExpressionException(None, msg) from e\nnltk.sem.logic.LogicalExpressionException: End of input found.  Expression expected.\nall x. ((AttendAndEngagedInSchoolEvents(Bonnie) & StudentWhoAttendsSchool(Bonnie)) | ((-AttendAndEngagedInSchoolEvents(Bonnie)) & (-StudentWhoAttendsSchool(Bonnie))) ->\n                                                                                                                                                                        ^\n"}
{"timestamp": "2025-06-14T16:41:52.157884", "premises": ["all x. (PerformInSchoolTalentShowsOften(x) -> AttendAndAreVeryEngagedWithSchoolEvents(x))", "all x. ((PerformInSchoolTalentShowsOften(x) & -InactiveAndDisinterestedInCommunity(x)) | (-PerformInSchoolTalentShowsOften(x) & InactiveAndDisinterestedInCommunity(x)))", "all x. (ChaperoneHighSchoolDances(x) -> -StudentWhoAttendsSchool(x))", "all x. (InactiveAndDisinterestedInCommunity(x) -> ChaperoneHighSchoolDances(x))", "all x. (YoungChildOrTeenager(x) & WishToFurtherAcademicCareerAndEducationalOpportunities(x) -> StudentWhoAttendsSchool(x))", "Bonnie = ((AttendAndAreVeryEngagedWithSchoolEvents(Bonnie) & StudentWhoAttendsSchool(Bonnie)) | ((-AttendAndAreVeryEngagedWithSchoolEvents(Bonnie)) & (-StudentWhoAttendsSchool(Bonnie))))"], "conclusion": "((YoungChildOrTeenager(Bonnie) & WishToFurtherAcademicCareerAndEducationalOpportunities(Bonnie) & ChaperoneHighSchoolDances(Bonnie)) | ((-YoungChildOrTeenager(Bonnie) & -WishToFurtherAcademicCareerAndEducationalOpportunities(Bonnie)))) -> ((StudentWhoAttendsSchool(Bonnie) | InactiveAndDisinterestedInCommunity(Bonnie)))", "error_type": "<class 'nltk.inference.prover9.Prover9FatalException'>", "error_message": "(FATAL)\n%%ERROR: The following symbols/arities are used as both relation and function symbols: AttendAndAreVeryEngagedWithSchoolEvents/1, StudentWhoAttendsSchool/1.\n\n\nFatal error:  The following symbols/arities are used as both relation and function symbols: AttendAndAreVeryEngagedWithSchoolEvents/1, StudentWhoAttendsSchool/1", "stack_trace": "Traceback (most recent call last):\n  File \"/data/gpfs/projects/punim0478/bansaab/linc2/eval/tasks/owafoltask.py\", line 568, in _process_neurosymbolic\n    parsed = json.loads(gen)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/json/__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/data/gpfs/projects/punim0478/bansaab/linc2/eval/tasks/utils.py\", line 217, in evaluate\n    truth_value = prover.prove(c, p_list)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/inference/api.py\", line 37, in prove\n    return self._prove(goal, assumptions, verbose)[0]\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/inference/prover9.py\", line 327, in _prove\n    stdout, returncode = self._call_prover9(\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/inference/prover9.py\", line 370, in _call_prover9\n    raise Prover9FatalException(returncode, errormsg)\nnltk.inference.prover9.Prover9FatalException: (FATAL)\n%%ERROR: The following symbols/arities are used as both relation and function symbols: AttendAndAreVeryEngagedWithSchoolEvents/1, StudentWhoAttendsSchool/1.\n\n\nFatal error:  The following symbols/arities are used as both relation and function symbols: AttendAndAreVeryEngagedWithSchoolEvents/1, StudentWhoAttendsSchool/1\n"}
{"timestamp": "2025-06-14T16:41:52.159833", "premises": ["all x. (PerformInSchoolTalentShowsOften(x) -> AttendAndVeryEngagedInSchoolEvents(x))", "all x. ((PerformInSchoolTalentShowsOften(x) & -InactiveAndDisinterestedMemberOfCommunity(x)) | (-PerformInSchoolTalentShowsOften(x) & InactiveAndDisinterestedMemberOfCommunity(x)))", "all x. (ChaperoneHighSchoolDances(x) -> -StudentWhoAttendsSchool(x))", "all x. (InactiveAndDisinterestedMemberOfCommunity(x) -> ChaperoneHighSchoolDances(x))", "all x. all y. (YoungChildOrTeenager(x) & WishToFurtherAcademicCareerAndEducationalOpportunities(x, y) -> StudentWhoAttendsSchool(x))", "(AttendAndVeryEngagedInSchoolEvents(Bonnie) & StudentWhoAttendsSchool(Bonnie)) | (-AttendAndVeryEngagedInSchoolEvents(Bonnie) & -StudentWhoAttendsSchool(Bonnie))"], "conclusion": "(ChaperoneHighSchoolDances(Bonnie) & YoungChildOrTeenager(Bonnie) & WishToFurtherAcademicCareerAndEducationalOpportunities(Bonnie) & -StudentWhoAttendsSchool(Bonnie)) | ((-ChaperoneHighSchoolDances(Bonnie) & -YoungChildOrTeenager(Bonnie) & -WishToFurtherAcademicCareerAndEducationalOpportunities(Bonnie)) -> (StudentWhoAttendsSchool(Bonnie) | InactiveAndDisinterestedMemberOfCommunity(Bonnie)))", "error_type": "<class 'nltk.inference.prover9.Prover9FatalException'>", "error_message": "(FATAL)\n%%ERROR: The following symbols are used with multiple arities: WishToFurtherAcademicCareerAndEducationalOpportunities/2, WishToFurtherAcademicCareerAndEducationalOpportunities/1.\n\n\nFatal error:  The following symbols are used with multiple arities: WishToFurtherAcademicCareerAndEducationalOpportunities/2, WishToFurtherAcademicCareerAndEducationalOpportunities/1", "stack_trace": "Traceback (most recent call last):\n  File \"/data/gpfs/projects/punim0478/bansaab/linc2/eval/tasks/owafoltask.py\", line 568, in _process_neurosymbolic\n    parsed = json.loads(gen)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/json/__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/data/gpfs/projects/punim0478/bansaab/linc2/eval/tasks/utils.py\", line 217, in evaluate\n    truth_value = prover.prove(c, p_list)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/inference/api.py\", line 37, in prove\n    return self._prove(goal, assumptions, verbose)[0]\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/inference/prover9.py\", line 327, in _prove\n    stdout, returncode = self._call_prover9(\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/inference/prover9.py\", line 370, in _call_prover9\n    raise Prover9FatalException(returncode, errormsg)\nnltk.inference.prover9.Prover9FatalException: (FATAL)\n%%ERROR: The following symbols are used with multiple arities: WishToFurtherAcademicCareerAndEducationalOpportunities/2, WishToFurtherAcademicCareerAndEducationalOpportunities/1.\n\n\nFatal error:  The following symbols are used with multiple arities: WishToFurtherAcademicCareerAndEducationalOpportunities/2, WishToFurtherAcademicCareerAndEducationalOpportunities/1\n"}
{"timestamp": "2025-06-14T16:41:52.159550", "premises": ["all x. (PerformInSchoolTalentShowsOften(x) -> AttendAndEngagedWithSchoolEvents(x))", "all x. ((PerformInSchoolTalentShowsOften(x) & -InactiveAndDisinterested(x)) | (-PerformInSchoolTalentShowsOften(x) & InactiveAndDisinterested(x)))", "all x. (ChaperoneHighSchoolDances(x) -> -StudentWhoAttendsSchool(x))", "all x. (InactiveAndDisinterested(x) -> ChaperoneHighSchoolDances(x))", "all x. all y. (YoungChildOrTeenager(x) & WishToFurtherAcademicCareerAndEducationalOpportunities(x, y) -> StudentWhoAttendsSchool(x))", "all x. ((AttendAndEngagedWithSchoolEvents(Bonnie) & StudentWhoAttendsSchool(Bonnie)) | (-AttendAndEngagedWithSchoolEvents(Bonnie) & -StudentWhoAttendsSchool(Bonnie)))"], "conclusion": "all x. ((YoungChildOrTeenager(Bonnie) & WishToFurtherAcademicCareerAndEducationalOpportunities(Bonnie) & ChaperoneHighSchoolDances(Bonnie)) | (-YoungChildOrTeenager(Bonnie) & -WishToFurtherAcademicCareerAndEducationalOpportunities(Bonnie))) -> ((StudentWhoAttendsSchool(Bonnie) | InactiveAndDisinterested(Bonnie)))", "error_type": "<class 'nltk.inference.prover9.Prover9FatalException'>", "error_message": "(FATAL)\n%%ERROR: The following symbols are used with multiple arities: WishToFurtherAcademicCareerAndEducationalOpportunities/2, WishToFurtherAcademicCareerAndEducationalOpportunities/1.\n\n\nFatal error:  The following symbols are used with multiple arities: WishToFurtherAcademicCareerAndEducationalOpportunities/2, WishToFurtherAcademicCareerAndEducationalOpportunities/1", "stack_trace": "Traceback (most recent call last):\n  File \"/data/gpfs/projects/punim0478/bansaab/linc2/eval/tasks/owafoltask.py\", line 568, in _process_neurosymbolic\n    parsed = json.loads(gen)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/json/__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/data/gpfs/projects/punim0478/bansaab/linc2/eval/tasks/utils.py\", line 217, in evaluate\n    truth_value = prover.prove(c, p_list)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/inference/api.py\", line 37, in prove\n    return self._prove(goal, assumptions, verbose)[0]\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/inference/prover9.py\", line 327, in _prove\n    stdout, returncode = self._call_prover9(\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/inference/prover9.py\", line 370, in _call_prover9\n    raise Prover9FatalException(returncode, errormsg)\nnltk.inference.prover9.Prover9FatalException: (FATAL)\n%%ERROR: The following symbols are used with multiple arities: WishToFurtherAcademicCareerAndEducationalOpportunities/2, WishToFurtherAcademicCareerAndEducationalOpportunities/1.\n\n\nFatal error:  The following symbols are used with multiple arities: WishToFurtherAcademicCareerAndEducationalOpportunities/2, WishToFurtherAcademicCareerAndEducationalOpportunities/1\n"}
{"timestamp": "2025-06-14T16:41:52.186906", "premises": ["all x. (PerformInSchoolTalentShowsOften(x) -> AttendAndVeryEngagedWithSchoolEvents(x))", "all x. ((PerformInSchoolTalentShowsOften(x) | InactiveAndDisinterestedMemberOfCommunity(x))", "all x. (ChaperoneHighSchoolDances(x) -> -StudentWhoAttendsSchool(x))", "all x. (InactiveAndDisinterestedMemberOfCommunity(x) -> ChaperoneHighSchoolDances(x))", "all x. all y. ((YoungChild(x) | Teenager(x)) & WishToFurtherAcademicCareer(x) & WishToFurtherEducationalOpportunities(x) -> StudentWhoAttendsSchool(x))", "(AttendsAndVeryEngagedWithSchoolEvents(Bonnie) & StudentWhoAttendsSchool(Bonnie)) | (-AttendsAndVeryEngagedWithSchoolEvents(Bonnie) & -StudentWhoAttendsSchool(Bonnie))"], "conclusion": "if (YoungChild(Bonnie) | Teenager(Bonnie) & WishToFurtherAcademicCareer(Bonnie) & WishToFurtherEducationalOpportunities(Bonnie) & ChaperoneHighSchoolDances(Bonnie)) | (-YoungChild(Bonnie) & -Teenager(Bonnie) & -WishToFurtherAcademicCareer(Bonnie) & -WishToFurtherEducationalOpportunities(Bonnie)), then (StudentWhoAttendsSchool(Bonnie) | InactiveAndDisinterestedMemberOfCommunity(Bonnie))", "error_type": "<class 'nltk.sem.logic.LogicalExpressionException'>", "error_message": "Unexpected token: '|'.  Expected token ')'.\nif (YoungChild(Bonnie) | Teenager(Bonnie) & WishToFurtherAcademicCareer(Bonnie) & WishToFurtherEducationalOpportunities(Bonnie) & ChaperoneHighSchoolDances(Bonnie)) | (-YoungChild(Bonnie) & -Teenager(Bonnie) & -WishToFurtherAcademicCareer(Bonnie) & -WishToFurtherEducationalOpportunities(Bonnie)), then (StudentWhoAttendsSchool(Bonnie) | InactiveAndDisinterestedMemberOfCommunity(Bonnie))\n                       ^", "stack_trace": "Traceback (most recent call last):\n  File \"/data/gpfs/projects/punim0478/bansaab/linc2/eval/tasks/owafoltask.py\", line 568, in _process_neurosymbolic\n    parsed = json.loads(gen)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/json/__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 154, in parse\n    result = self.process_next_expression(None)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 290, in process_next_expression\n    accum = self.handle(tok, context)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 303, in handle\n    return self.handle_variable(tok, context)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 359, in handle_variable\n    self.assertNextToken(Tokens.CLOSE)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 573, in assertNextToken\n    raise UnexpectedTokenException(self._currentIndex, tok, expected)\nnltk.sem.logic.UnexpectedTokenException: Unexpected token: '|'.  Expected token ')'.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/data/gpfs/projects/punim0478/bansaab/linc2/eval/tasks/utils.py\", line 213, in evaluate\n    c = read_expr(conclusion)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 957, in fromstring\n    return cls._logic_parser.parse(s, signature)\n  File \"/home/bansaab/.conda/envs/neurosymbolic/lib/python3.10/site-packages/nltk/sem/logic.py\", line 159, in parse\n    raise LogicalExpressionException(None, msg) from e\nnltk.sem.logic.LogicalExpressionException: Unexpected token: '|'.  Expected token ')'.\nif (YoungChild(Bonnie) | Teenager(Bonnie) & WishToFurtherAcademicCareer(Bonnie) & WishToFurtherEducationalOpportunities(Bonnie) & ChaperoneHighSchoolDances(Bonnie)) | (-YoungChild(Bonnie) & -Teenager(Bonnie) & -WishToFurtherAcademicCareer(Bonnie) & -WishToFurtherEducationalOpportunities(Bonnie)), then (StudentWhoAttendsSchool(Bonnie) | InactiveAndDisinterestedMemberOfCommunity(Bonnie))\n                       ^\n"}
